### PR TITLE
Add Section 2

### PR DESCRIPTION
**Pull request by canyon289**

### CODE REVIEW

**Comment by aloctavodia** [comment]
LGTM!

**Comment by ColCarroll** [comment]
Looks good to me, too! We might add exercises for when you _can_ convert to a dataframe, and when you can't.

**Comment by canyon289** [comment]
> Looks good to me, too! We might add exercises for when you _can_ convert to a dataframe, and when you can't.

Convert a xarray to a dataframe?

**Comment by canyon289** [comment]
Ready for review again. Just need review on notebooks in Section 2

Outstanding Items
@ColCarroll Could use a matplotlib animation of a sampler!

Questions
My verbiage around samples and draws is really loose. I could use help here. From what I understand

1. MCMC samplers are algorithms that sample from posterior distribution
2. Draws are the result of each sample?

**Comment by canyon289** [comment]
Still needs review but merging and keep tracking with this issue https://github.com/arviz-devs/bayesian-model-evaluation/issues/26

**Pull request merged**
