### PR TITLE
Convert notebook to external radon dataset

### PR DESCRIPTION
**Pull request by canyon289**
@ColCarroll I could really use your help on the error below. The ENV is frozen to ArviZ 0.4.0 and PyMC3 3.6 but this started appearing all of a sudden and I'm not sure why.

Do you have any ideas why this is happening now? Also a fix because this bug basically breaks the whole tutorial :(

Full stack trace is in the notebook

image

### CODE REVIEW

**Comment by canyon289** [comment]
Created an ArviZ issue here https://github.com/arviz-devs/arviz/issues/692

**Comment by ColCarroll** [comment]
Looks like you fixed this -- let me know if you want me to verify the fix on this PR and merge.

**Comment by canyon289** [comment]
I'll install ArviZ from github master, rerun, and merge so the notebooks are rendered correctly in master. Will do this shortly

**Comment by canyon289** [comment]
Done!

**Pull request merged**
